version: "2"
run:
  timeout: 10m
linters:
  default: standard
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - decorder
    - depguard
    - dogsled
    - durationcheck
    - errcheck
    - exhaustive
    - forbidigo
    - forcetypeassert
    - goconst
    - gocritic
    - godot
    - goheader
    - gosec
    - govet
    - grouper
    - importas
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
  disable:
    - mnd
  settings:
    depguard:
      rules:
        Main:
          list-mode: lax
          allow:
            - $all
    exhaustive:
      # Presence of "default" case in switch statements satisfies exhaustiveness
      default-signifies-exhaustive: true
    goheader:
      values:
        regexp:
          COPYRIGHT-HOLDER: Copyright © {{ MOD-YEAR-RANGE }} Michael Fero
      template-path: .header
    goconst:
      min-occurrences: 10
    misspell:
      locale: US
    revive:
      rules:
        - name: package-comments
          disabled: true
  exclusions:
    paths:
      - _test.go
      - third_party$
      - builtin$
      - examples$
